export const productsData = [
  {
    id: "1",
    domain_id: "education",
    name: "Campus Security Suite",
    slug: "campus-security-suite",
    description: "Comprehensive security solution for educational institutions",
    image_url: null,
    category: "Security",
    tags: ["security", "access-control", "monitoring"],
    price: 9999,
    currency: "USD",
    features: [
      "Multi-camera integration",
      "Real-time alerts",
      "Access control",
      "Visitor management",
    ],
    is_active: true,
    order_index: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: "2",
    domain_id: "education",
    name: "Smart Attendance System",
    slug: "smart-attendance-system",
    description: "Automated attendance tracking with biometric verification",
    image_url: null,
    category: "Operations",
    tags: ["attendance", "biometric", "automation"],
    price: 4999,
    currency: "USD",
    features: [
      "Biometric scanning",
      "Real-time reporting",
      "Mobile app integration",
      "Historical analytics",
    ],
    is_active: true,
    order_index: 2,
    created_at: null,
    updated_at: null,
  },
  {
    id: "3",
    domain_id: "healthcare",
    name: "Patient Monitoring Hub",
    slug: "patient-monitoring-hub",
    description: "Central monitoring system for hospital ICU and wards",
    image_url: null,
    category: "Healthcare",
    tags: ["monitoring", "hospital", "icu"],
    price: 15999,
    currency: "USD",
    features: [
      "Vital sign tracking",
      "Alert system",
      "Data logging",
      "Multi-room support",
    ],
    is_active: true,
    order_index: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: "4",
    domain_id: "manufacturing",
    name: "Factory Floor Analytics",
    slug: "factory-floor-analytics",
    description: "Real-time production monitoring and optimization",
    image_url: null,
    category: "Manufacturing",
    tags: ["production", "iot", "analytics"],
    price: 19999,
    currency: "USD",
    features: [
      "Real-time tracking",
      "Production metrics",
      "Downtime alerts",
      "Historical data",
    ],
    is_active: true,
    order_index: 1,
    created_at: null,
    updated_at: null,
  },
];
